version: '3.7'
services:
  db:
    image: 'postgres'
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
      POSTGRES_DB: 'mydb'
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build: .
    environment:
      DATABASE_URL: 'postgresql://docker:123456@db:5432/mydb?schema=public'
    ports:
      - "4000:4000"
    volumes:
      - .:/app/
      - /app/node_modules
   # Run the caddy server
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
  # nginx:
  #       restart: always
  #       build:
  #           context: ./nginx
  #       ports:
  #           - "80:80"
volumes:
  postgres:
  caddy:
